# Generated by Django 2.2.6 on 2019-10-19 15:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virgin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
