# Generated by Django 2.2.6 on 2019-10-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virgin', '0007_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Productcategory',
                'verbose_name_plural': 'Productcategory',
                'db_table': 'Productcategory',
            },
        ),
        migrations.CreateModel(
            name='Productsubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Productsubcategory',
                'verbose_name_plural': 'Productsubcategory',
                'db_table': 'Productsubcategory',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
