# Generated by Django 2.2.6 on 2019-11-01 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virgin', '0010_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Granite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virgin.Category')),
            ],
            options={
                'verbose_name': 'granite',
                'verbose_name_plural': 'granite',
                'db_table': 'granite',
            },
        ),
    ]
