# Generated by Django 2.2.6 on 2019-11-01 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virgin', '0011_granite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='granite',
            name='Category',
        ),
    ]
