# Generated by Django 2.2.6 on 2019-11-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virgin', '0012_remove_granite_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'banners',
                'verbose_name_plural': 'banners',
                'db_table': 'banners',
            },
        ),
    ]
