# Generated by Django 2.2.6 on 2019-11-03 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('virgin', '0013_banners'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'ProductCategoryImages',
                'verbose_name_plural': 'ProductCategoryImages',
                'db_table': 'ProductCategoryImages',
            },
        ),
        migrations.CreateModel(
            name='ProductSubCategoryImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'ProductSubCategoryImages',
                'verbose_name_plural': 'ProductSubCategoryImages',
                'db_table': 'ProductSubCategoryImages',
            },
        ),
        migrations.DeleteModel(
            name='Granite',
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'ProductCategory', 'verbose_name_plural': 'ProductCategory'},
        ),
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'verbose_name': 'ProductSubCategory', 'verbose_name_plural': 'ProductSubCategory'},
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='virgin.ProductCategory'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='ProductCategory',
        ),
        migrations.AlterModelTable(
            name='productsubcategory',
            table='ProductSubCategory',
        ),
        migrations.AddField(
            model_name='productsubcategoryimages',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virgin.ProductSubCategory'),
        ),
        migrations.AddField(
            model_name='productcategoryimages',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virgin.ProductCategory'),
        ),
    ]
