# Generated by Django 2.2.6 on 2019-11-03 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virgin', '0014_auto_20191103_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='enable_on_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='enable_on_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productcategoryimages',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virgin.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virgin.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='productsubcategoryimages',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virgin.ProductSubCategory'),
        ),
    ]
